# Generated by Django 3.2.17 on 2023-03-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(max_length=64, verbose_name="Имя проекта")),
                ("link", models.URLField(max_length=64, null=True, verbose_name="Ссылка на репозиторий")),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проект",
            },
        ),
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=1024, verbose_name="Текст заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todoapp.project", verbose_name="Проект"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметка",
            },
        ),
    ]
